import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F2F0F8',
        padding: 10,
    },
    header: {
        alignItems: 'center',
        marginBottom: 20,
    },
    boxImagem: {
        alignSelf: 'flex-end',
        marginBottom: 10,
    },
    titulo: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1E293B',
        textAlign: 'center',
        marginBottom: 30,
    },
    perfisContainer: {
        marginBottom: 30,
    },
    subtitulo: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1E293B',
        marginBottom: 15,
        textAlign: 'center',
    },
    listaPerfis: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 15,
    },
    perfilItem: {
        alignItems: 'center',
        width: 150,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        marginBottom: 10,
    },
    nomeCrianca: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1E293B',
        textAlign: 'center',
    },
    idadeCrianca: {
        fontSize: 14,
        color: '#64748B',
        textAlign: 'center',
    },
    novoPerfil: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 150,
        backgroundColor: '#EFF6FF',
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        borderWidth: 2,
        borderColor: '#BFDBFE',
        borderStyle: 'dashed',
    },
    maisIcon: {
        fontSize: 32,
        color: '#3B82F6',
        marginBottom: 5,
    },
    novoPerfilTexto: {
        fontSize: 16,
        color: '#3B82F6',
        fontWeight: '600',
        textAlign: 'center',
    },
    mensagemContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    textoMensagem: {
        fontSize: 16,
        color: '#475569',
        lineHeight: 24,
        marginBottom: 10,
        textAlign: 'center',
    },
    botao: {
        backgroundColor: '#4F46E5',
        borderRadius: 8,
        padding: 16,
        alignItems: 'center',
        marginTop: 15,
    },
    textoBotao: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
})